server:
  port: 8085
spring:
  application:
    name: loginDEMO
  datasource:
    url: jdbc:h2:~/.loginDEMO/database
    driver-class-name: org.h2.Driver
    username: admin
    password: 123456
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2admin
      enabled: true
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
    template-loader-path: classpath:/templates/
    suffix: .ftl